apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingbackend
spec:
  selector:
    matchLabels:
      app: votingbackend
  replicas: 1
  template:
    metadata:
      labels:
        app: votingbackend
    spec:
      containers:
      - name: votingbackend
        image: bretfisher/examplevotingapp_result
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: votingbackend-service
spec:
  selector:
    app: votingbackend
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
