apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingfrontend
spec:
  selector:
    matchLabels:
      app: votingfrontend
  replicas: 1
  template:
    metadata:
      labels:
        app: votingfrontend
    spec:
      containers:
      - name: votingfrontend
        image: bretfisher/examplevotingapp_vote
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: votingfrontend-service
spec:
  selector:
    app: votingfrontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  